watch_stylesheet: true
watch_config: true
debug: false

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: false
      round_corners: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 0 # 4 4 2 4
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "win_button",
          "lines",
          "clock",
          "lines",
          "glazewm_workspaces",
          # "lines",
          "taskbar",
        ]
      center: []
      right:
        [
          "lines",
          "media",
          "cava",
          "volume",
          "lines",
          "systray",
          "wallpapers",
          "power_menu",
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "家"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\sakanai\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\sakanai\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\sakanai\\Pictures" }
        - { title: "Videos", path: "C:\\Users\\sakanai\\Videos" }
      system_menu: false
      power_menu: false
      blur: false
      round_corners: false
      round_corners_type: "normal"
      distance: 5
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "up"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "c5d620068f1644148ec153739261203"
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Tver"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      label_alt: "{artist}"
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 45
        label_alt: 45
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: false
      thumbnail_alpha: 250
      thumbnail_padding: 8
      thumbnail_corner_radius: 6
      icons:
        prev_track: ""
        next_track: ""
        play: "<span>\uf001</span>"
        pause: "<span>\uf001</span>"
      media_menu:
        blur: false
        round_corners: false
        round_corners_type: "normal"
        alignment: "right"
        direction: "up"
        offset_top: 5
        offset_left: 0
        thumbnail_size: 100
        thumbnail_corner_radius: 0
        max_title_size: 55
        max_artist_size: 50
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        direction: "up"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %b %d %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      tooltip: false
      timezones: []
      calendar:
        alignment: "center"
        direction: "up"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span>"
      label_alt: "<span>\uf473</span>"
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: false
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "up"
        distance: 6
      callbacks:
        on_left: "toggle_group"
        on_middle: "toggle_label"
        on_right: "exec explorer C:\\" # Open disk C in file explorer
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\sakanai\\Pictures\\walls"
      change_automatically: false
      update_interval: 60
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
      gallery:
        enabled: true
        blur: true
        image_width: 300
        image_per_page: 6
        show_buttons: true
        orientation: "landscape"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 0
        enable_cache: true
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        signout: ["", "Sign out"]
        shutdown: ["", "Shut Down"]
        restart: ["", "Restart"]
        hibernate: ["", "Hibernate"]
        cancel: ["", "Cancel"]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 0
      reverse: 0
      sensitivity: 90
      bars_number: 12
      bar_spacing: 2
      bar_width: 4
      foreground: "#DDC7A1"
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 0
        left: 2
        bottom: 0
        right: 0
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications;
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "right"
        direction: "up"
        distance: 6
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ue8a9"
      label_expanded: "\ue76c"
      icon_size: 16
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 0
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: true
        show: "always"
        min_length: 6
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  lines:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\u007c"
      label_alt: "\u007c"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "家"
      label_alt: "家"
      class_name: "system-widget"
      callbacks:
        on_left: "exec start_menu"
